### PR TITLE
Response Status Codes

### PR DESCRIPTION
**Pull request by zwebb**
This slightly edits the handler function, so that if a status code is passed along with a subroute's response, it will be applied to the HTTP response.

### CODE REVIEW

**Comment by object88** [comment]
So, this means that if there is an object returned, the object must be shaped as:
`{ result: [foo] }`, with an optional `code` property.

This behavior needs to be VERY well documented, because this:
```
var s1 = "test string"
var s2 = new String("test string 2")
```
`typeof s1` -> `string`
`typeof s2` -> `object`

I'm pretty sure that there's little JS code which creates a String object, so really, it's probably never going to bite us.

That said, I wonder if it would be better to just always expect an object.  If someone wants to set headers in the future, for example, it would set us up for more consistent behavior.

**Comment by object88** [comment]
Another option, to increase clarity, might be to leave the behavior behind the `handler` function the same, but introduce a new `handler2` callback function, which expects an object as the return value, from which the user may be able to detail fun things like header values, status code, etc.

**Comment by TorinFrancis** [comment]
I would also add that `typeof null == 'object'` evaluates to `true`.

It may be better to have something like
```
function Response(response, code) {
  this.response = response;
  this.code = code;
}
```
and then
```
if (response instanceof Response) {
...
```

**Comment by object88** [comment]
I like the way this is handled now, and it looks like it would be easy to merge back into divmain/drydock.  Very well done, team!

**Comment by object88** [comment]
👍

**Pull request merged**
